name: tourify_sample_project
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/busimage1.jpg
    - images/busimage2.jpg
    - images/busimage3.jpg
    - images/busimage4.jpg
    - images/busimage5.jpg
    - images/busimage6.jpg
    - images/busimage7.jpg
    - images/busimage8.jpeg
    - images/busimage9.jpeg
    - images/car1.jpg
    - images/car2.jpg
    - images/car3.jpg
