// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv6qVjIsmZfUT9iIUCzZkAZC7tgPLbCoQ',
    appId: '1:988846954874:web:3419e55e4677b0c7219ec3',
    messagingSenderId: '988846954874',
    projectId: 'tourify-221',
    authDomain: 'tourify-221.firebaseapp.com',
    storageBucket: 'tourify-221.firebasestorage.app',
    measurementId: 'G-E46E0YHNLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCarVZqvQlyKFvJj2xFnR0sJl9kj2bOfeQ',
    appId: '1:988846954874:android:9288715502b6a82d219ec3',
    messagingSenderId: '988846954874',
    projectId: 'tourify-221',
    storageBucket: 'tourify-221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-D7l85cBxBj7tL3RUQ9ZldY8qGTN0jko',
    appId: '1:988846954874:ios:c21e54afabf98250219ec3',
    messagingSenderId: '988846954874',
    projectId: 'tourify-221',
    storageBucket: 'tourify-221.firebasestorage.app',
    iosBundleId: 'com.example.tourifySampleProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv6qVjIsmZfUT9iIUCzZkAZC7tgPLbCoQ',
    appId: '1:988846954874:web:cbcc6b45290880de219ec3',
    messagingSenderId: '988846954874',
    projectId: 'tourify-221',
    authDomain: 'tourify-221.firebaseapp.com',
    storageBucket: 'tourify-221.firebasestorage.app',
    measurementId: 'G-K3CVFW992M',
  );
}